vich_uploader:
    db_driver: orm

    mappings:
        book_cover:
            uri_prefix: /uploads/images/book/cover
            upload_destination: '%kernel.project_dir%/public/uploads/images/book/cover'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        user_profile:
            uri_prefix: /uploads/images/user/profile
            upload_destination: '%kernel.project_dir%/public/uploads/images/user/profile'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
